// Code generated by "stringer -type SynchroEvent -output synchro_string.go"; DO NOT EDIT.

package duo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SynchroMessage-0]
	_ = x[SynchroReset-1]
	_ = x[SynchroSync-2]
	_ = x[SynchroOutOfSync-3]
}

const _SynchroEvent_name = "SynchroMessageSynchroResetSynchroSyncSynchroOutOfSync"

var _SynchroEvent_index = [...]uint8{0, 14, 26, 37, 53}

func (i SynchroEvent) String() string {
	if i < 0 || i >= SynchroEvent(len(_SynchroEvent_index)-1) {
		return "SynchroEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SynchroEvent_name[_SynchroEvent_index[i]:_SynchroEvent_index[i+1]]
}
