// Code generated by "stringer -type PowerOverloadCbEventIdT,RspDuoModeCbEventIdT,EventT -output callback_string.go"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Overload_Detected-0]
	_ = x[Overload_Corrected-1]
}

const _PowerOverloadCbEventIdT_name = "Overload_DetectedOverload_Corrected"

var _PowerOverloadCbEventIdT_index = [...]uint8{0, 17, 35}

func (i PowerOverloadCbEventIdT) String() string {
	if i < 0 || i >= PowerOverloadCbEventIdT(len(_PowerOverloadCbEventIdT_index)-1) {
		return "PowerOverloadCbEventIdT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PowerOverloadCbEventIdT_name[_PowerOverloadCbEventIdT_index[i]:_PowerOverloadCbEventIdT_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PrimaryInitialised-0]
	_ = x[SecondaryAttached-1]
	_ = x[SecondaryDetached-2]
	_ = x[SecondaryInitialised-3]
	_ = x[SecondaryUninitialised-4]
	_ = x[PrimaryDllDisappeared-5]
	_ = x[SecondaryDllDisappeared-6]
}

const _RspDuoModeCbEventIdT_name = "PrimaryInitialisedSecondaryAttachedSecondaryDetachedSecondaryInitialisedSecondaryUninitialisedPrimaryDllDisappearedSecondaryDllDisappeared"

var _RspDuoModeCbEventIdT_index = [...]uint8{0, 18, 35, 52, 72, 94, 115, 138}

func (i RspDuoModeCbEventIdT) String() string {
	if i < 0 || i >= RspDuoModeCbEventIdT(len(_RspDuoModeCbEventIdT_index)-1) {
		return "RspDuoModeCbEventIdT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RspDuoModeCbEventIdT_name[_RspDuoModeCbEventIdT_index[i]:_RspDuoModeCbEventIdT_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GainChange-0]
	_ = x[PowerOverloadChange-1]
	_ = x[DeviceRemoved-2]
	_ = x[RspDuoModeChange-3]
}

const _EventT_name = "GainChangePowerOverloadChangeDeviceRemovedRspDuoModeChange"

var _EventT_index = [...]uint8{0, 10, 29, 42, 58}

func (i EventT) String() string {
	if i < 0 || i >= EventT(len(_EventT_index)-1) {
		return "EventT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventT_name[_EventT_index[i]:_EventT_index[i+1]]
}
