// Code generated by "stringer -type TransferModeT -output dev_string.go"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ISOCH-0]
	_ = x[BULK-1]
}

const _TransferModeT_name = "ISOCHBULK"

var _TransferModeT_index = [...]uint8{0, 5, 9}

func (i TransferModeT) String() string {
	if i < 0 || i >= TransferModeT(len(_TransferModeT_index)-1) {
		return "TransferModeT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TransferModeT_name[_TransferModeT_index[i]:_TransferModeT_index[i+1]]
}
