// Code generated by "stringer -type Rsp2_AntennaSelectT,Rsp2_AmPortSelectT -output rsp2_string.go"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Rsp2_ANTENNA_A-5]
	_ = x[Rsp2_ANTENNA_B-6]
}

const _Rsp2_AntennaSelectT_name = "Rsp2_ANTENNA_ARsp2_ANTENNA_B"

var _Rsp2_AntennaSelectT_index = [...]uint8{0, 14, 28}

func (i Rsp2_AntennaSelectT) String() string {
	i -= 5
	if i < 0 || i >= Rsp2_AntennaSelectT(len(_Rsp2_AntennaSelectT_index)-1) {
		return "Rsp2_AntennaSelectT(" + strconv.FormatInt(int64(i+5), 10) + ")"
	}
	return _Rsp2_AntennaSelectT_name[_Rsp2_AntennaSelectT_index[i]:_Rsp2_AntennaSelectT_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Rsp2_AMPORT_1-1]
	_ = x[Rsp2_AMPORT_2-0]
}

const _Rsp2_AmPortSelectT_name = "Rsp2_AMPORT_2Rsp2_AMPORT_1"

var _Rsp2_AmPortSelectT_index = [...]uint8{0, 13, 26}

func (i Rsp2_AmPortSelectT) String() string {
	if i < 0 || i >= Rsp2_AmPortSelectT(len(_Rsp2_AmPortSelectT_index)-1) {
		return "Rsp2_AmPortSelectT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Rsp2_AmPortSelectT_name[_Rsp2_AmPortSelectT_index[i]:_Rsp2_AmPortSelectT_index[i+1]]
}
