// Code generated by "stringer -type RspDx_AntennaSelectT,RspDx_HdrModeBwT -output rspdx_string.go"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RspDx_ANTENNA_A-0]
	_ = x[RspDx_ANTENNA_B-1]
	_ = x[RspDx_ANTENNA_C-2]
}

const _RspDx_AntennaSelectT_name = "RspDx_ANTENNA_ARspDx_ANTENNA_BRspDx_ANTENNA_C"

var _RspDx_AntennaSelectT_index = [...]uint8{0, 15, 30, 45}

func (i RspDx_AntennaSelectT) String() string {
	if i < 0 || i >= RspDx_AntennaSelectT(len(_RspDx_AntennaSelectT_index)-1) {
		return "RspDx_AntennaSelectT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RspDx_AntennaSelectT_name[_RspDx_AntennaSelectT_index[i]:_RspDx_AntennaSelectT_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RspDx_HDRMODE_BW_0_200-0]
	_ = x[RspDx_HDRMODE_BW_0_500-1]
	_ = x[RspDx_HDRMODE_BW_1_200-2]
	_ = x[RspDx_HDRMODE_BW_1_700-3]
}

const _RspDx_HdrModeBwT_name = "RspDx_HDRMODE_BW_0_200RspDx_HDRMODE_BW_0_500RspDx_HDRMODE_BW_1_200RspDx_HDRMODE_BW_1_700"

var _RspDx_HdrModeBwT_index = [...]uint8{0, 22, 44, 66, 88}

func (i RspDx_HdrModeBwT) String() string {
	if i < 0 || i >= RspDx_HdrModeBwT(len(_RspDx_HdrModeBwT_index)-1) {
		return "RspDx_HdrModeBwT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RspDx_HdrModeBwT_name[_RspDx_HdrModeBwT_index[i]:_RspDx_HdrModeBwT_index[i+1]]
}
