// Code generated by "stringer -type RspDuo_AmPortSelectT -output rspduo_string.go"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RspDuo_AMPORT_1-1]
	_ = x[RspDuo_AMPORT_2-0]
}

const _RspDuo_AmPortSelectT_name = "RspDuo_AMPORT_2RspDuo_AMPORT_1"

var _RspDuo_AmPortSelectT_index = [...]uint8{0, 15, 30}

func (i RspDuo_AmPortSelectT) String() string {
	if i < 0 || i >= RspDuo_AmPortSelectT(len(_RspDuo_AmPortSelectT_index)-1) {
		return "RspDuo_AmPortSelectT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RspDuo_AmPortSelectT_name[_RspDuo_AmPortSelectT_index[i]:_RspDuo_AmPortSelectT_index[i+1]]
}
